import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { NuqsAdapter } from 'nuqs/adapters/next/app';
import { ClerkProvider } from '@clerk/nextjs';
import { cn } from '@/lib/utils';

import './globals.css';

const inter = Inter({
	variable: '--font-primary',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang='en'>
				<body className={cn(inter.variable, 'antialiased')}>
					<div className='container grid min-h-screen py-layout-gutter-y'>
						<NuqsAdapter>{children}</NuqsAdapter>
					</div>
				</body>
			</html>
		</ClerkProvider>
	);
}
